import React from "react";
import { Metadata } from "next";
import { FileText, AlertTriangle, Scale, ShieldAlert } from "lucide-react";
import { AdSlot } from "@/components/AdSlot";

export const metadata: Metadata = {
  title: "Terms of Service & Disclaimer | ShieldTools",
  description:
    "Review the Terms of Service and legal disclaimers governing the use of ShieldTools DocShield and EcomShield utilities.",
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-4xl px-4 py-12 sm:px-6 lg:px-8">
      {/* Top Header Ad */}
      <AdSlot id="terms-top" format="header-leaderboard" />

      <div className="text-center">
        <span className="rounded-full bg-blue-50 px-3.5 py-1 text-xs font-bold text-blue-600 dark:bg-blue-950/60 dark:text-blue-400">
          User Agreement
        </span>
        <h1 className="mt-4 text-3xl sm:text-4xl font-black tracking-tight text-slate-900 dark:text-white">
          Terms of Service & Disclaimer
        </h1>
        <p className="mt-2 text-xs text-slate-500 dark:text-slate-400">
          Effective Date: September 16, 2026
        </p>
      </div>

      <div className="mt-10 space-y-8 rounded-2xl border border-slate-200 bg-white p-6 sm:p-10 shadow-sm dark:border-slate-800 dark:bg-slate-900 text-xs sm:text-sm leading-relaxed text-slate-700 dark:text-slate-300">
        {/* Section 1 */}
        <section className="space-y-3">
          <h2 className="text-base font-bold text-slate-900 dark:text-white">
            1. Acceptance of Terms
          </h2>
          <p>
            By accessing or using the ShieldTools website (tools.talhaweb.xyz), its standalone embeddable widgets, or related documentation, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the website or its embedded widgets.
          </p>
        </section>

        {/* Section 2: Non-Financial & Non-Legal Advice Disclaimer */}
        <section className="space-y-3 rounded-xl border border-amber-500/30 bg-amber-50/50 p-4 dark:border-amber-500/20 dark:bg-amber-950/20">
          <div className="flex items-center gap-2 font-bold text-amber-900 dark:text-amber-200">
            <AlertTriangle className="h-4 w-4" />
            <span>Important: Non-Financial & Non-Legal Advice Disclaimer</span>
          </div>
          <p className="text-xs text-amber-800 dark:text-amber-300">
            The calculations, metrics, break-even estimations, and risk health statuses generated by <strong>EcomShield™</strong> are provided strictly for educational and modeling purposes. They do not constitute formal financial, accounting, auditing, or tax advice. Actual business results will vary depending on courier agreements, chargebacks, customer returns, seasonal advertising costs, and inventory shrink.
          </p>
          <p className="text-xs text-amber-800 dark:text-amber-300">
            Similarly, watermarks generated via <strong>DocShield™</strong> are visual deterrents designed to deter unauthorized secondary reuse. ShieldTools makes no representation or warranty that any third-party bank, telecommunication operator, government agency, or judicial court will accept or reject any particular watermarked document scan. Users are responsible for confirming identity verification guidelines with their specific counterparty.
          </p>
        </section>

        {/* Section 3 */}
        <section className="space-y-3">
          <h2 className="text-base font-bold text-slate-900 dark:text-white">
            2. Permitted Use & Code of Conduct
          </h2>
          <p>
            You agree to use ShieldTools solely for lawful purposes. You shall NOT:
          </p>
          <ul className="list-disc pl-5 space-y-1 text-slate-600 dark:text-slate-400">
            <li>Use the watermarking studio to forge, falsify, or alter government identity documents in violation of federal, national, or local laws.</li>
            <li>Attempt to reverse-engineer, exploit, or cause automated denial-of-service traffic spikes on our web assets.</li>
            <li>Modify or strip the &quot;Powered by ShieldTools&quot; viral attribution links from embedded iframe widgets without express written authorization.</li>
          </ul>
        </section>

        {/* Section 4 */}
        <section className="space-y-3">
          <h2 className="text-base font-bold text-slate-900 dark:text-white">
            3. Limitation of Liability
          </h2>
          <p>
            To the maximum extent permitted by applicable law, ShieldTools, its authors, contributors, and hosting providers shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, loss of data, identity theft incidents, business interruption, or courier disputes arising out of your access to or inability to use the platform.
          </p>
        </section>

        {/* Section 5 */}
        <section className="space-y-3">
          <h2 className="text-base font-bold text-slate-900 dark:text-white">
            4. Third-Party Links & Advertisements
          </h2>
          <p>
            Our website displays third-party sponsor advertisements provided by networks such as Google AdSense. ShieldTools does not endorse, verify, or guarantee the goods, services, or claims advertised by external sponsors. Any engagement with advertisers is strictly between you and the respective third party.
          </p>
        </section>

        {/* Section 6 */}
        <section className="space-y-3">
          <h2 className="text-base font-bold text-slate-900 dark:text-white">
            5. Governing Law & Jurisdiction
          </h2>
          <p>
            These Terms shall be interpreted and governed in accordance with international web standards and the laws of the operating jurisdiction, without regard to its conflict of law principles.
          </p>
        </section>
      </div>

      {/* Bottom In-Feed Ad */}
      <AdSlot id="terms-bottom" format="in-feed-banner" />
    </div>
  );
}
